version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - enhancement
    commit-message:
      prefix: chore
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - enhancement
    commit-message:
      prefix: ci
    groups:
      actions:
        update-types:
          - minor
          - patch
